### ISSUE TITLE
Null Reference Exception on Some Events

### ISSUE THREAD

**Issue by ThinkFr33ly** [bytenik/Seq.App.Slack#1]
I'm getting the following NRE:

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Seq.Slack.SlackReactor.On(Event`1 evt)
       at Seq.Server.Features.Runner.AppHost.SendLogEventData(ISubscribeTo`1 reactor, DateTime utcTimestamp, Int64 arrivalOrder, UInt32 hash, String document) in c:\TeamCity\buildAgent\work\9b28c0a5c864e317\src\Seq.Server\Server\Features\Runner\AppHost.cs:line 280
       at Seq.Server.Features.Runner.AppHost.Send(StorageEvent storageEvent) in c:\TeamCity\buildAgent\work\9b28c0a5c864e317\src\Seq.Server\Server\Features\Runner\AppHost.cs:line 230

Below is the JSON for the event in question:

    {
      "Timestamp": "2014-06-10T21:49:30.8195903+00:00",
      "Properties": [],
      "MessageTemplateTokens": [
        {
          "Text": "Warning: pattern spec/smoketests/*.js did not match any files.\nStarting selenium standalone server...\nSelenium standalone server started at http://10.50.1.5:63040/wd/hub\n\u001b[32m.\u001b[0m\u001b[32m.\u001b[0m\n\nFinished in 21.423 seconds\n\u001b[32m2 tests, 9 assertions, 0 failures\n\u001b[0m\nShutting down selenium standalone server."
        }
      ],
      "EventType": "$F7AD4BEE",
      "Level": "Information",
      "Id": "event-fe5d603f530c08d13403000000000000",
      "Links": {
        "Self": "api/events/event-fe5d603f530c08d13403000000000000{?download,render}",
        "Group": "api/events/resources"
      }
    }

It's hard to tell what specific event is causing the issue. I'll keep trying to narrow it down.

**Comment by bytenik** [comment]
Fixed this. Sorry it took so long -- I've been super swamped.
