### ISSUE TITLE
TLS/SSL issue when running on machines with deactivated TLS cipher suites

### ISSUE THREAD

**Issue by bronumski** [bytenik/Seq.App.Slack#33]
We recently deactivated the older less secure cipher suites on our machines meaning that the slack notifications cannot be sent. They fail with the following exception.

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Seq.App.Slack.SlackApi.SendMessage(String webhookUrl, SlackMessage message)
   at Seq.App.Slack.SlackReactor.On(Event`1 evt)
   at Seq.Apps.GenericHost.AppHost.<SendAsync>d__19.MoveNext()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---<---
```

This is because older versions of .net do not use TLS 1.2+ by default. This can be resolved by either migrating to at least net 4.7.1 (currently the project is at 4.5.2). Or adding the following line (which might require an update to at least net 4.6.x).

```
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
```

Depending on how the plugin is hosted it might need the above line regardless of moving to net 4.7.1

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by nblumhardt** [comment]
Thanks for the report, Matt. This sounds like something best approached from the host process side (rather than in just this one app specifically), so I've created an additional ticket https://github.com/datalust/seq-tickets/issues/775 to track it.

**Comment by bronumski** [comment]
Installing the latest version of seq ([datalust/seq-tickets#775](https://github.com/datalust/seq-tickets/issues/775)) resolved this issue without having to update the app.
